spring:
  profiles:
    active: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
    database-platform: org.hibernate.dialect.MySQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret-key: ${WEBGAM_JWT_SECRET_KEY}

webgam:
  admin-password: ${WEBGAM_ADMIN_PASSWORD}
  dev-password: ${WEBGAM_DEV_PASSWORD}

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/webgam_db
    username: webgam_admin
    password: WEBGAM_admin_01

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework.security: TRACE

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/webgam_db_test
    username: webgam_admin
    password: WEBGAM_admin_01

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework.security: TRACE

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${WEBGAM_DB_DEV_URL}
    username: ${WEBGAM_DB_DEV_USERNAME}
    password: ${WEBGAM_DB_DEV_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${WEBGAM_DB_URL}
    username: ${WEBGAM_DB_USERNAME}
    password: ${WEBGAM_DB_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
