spring:
  profiles:
    active: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret-key: QeShVmYq3t6w9z$C&F)J@NcRfUjWnZr4

webgam:
  admin-password: ~
  dev-password: ~

logging:
  slack:
    webhook-uri: https://hooks.slack.com/services/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


---

spring:
  config:
    activate:
      on-profile: dev

secret-name: dev/webgam-server

---

spring:
  config:
    activate:
      on-profile: prod

secret-name: prod/webgam-server
