spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/webgam_db
    username: webgam_admin
    password: WEBGAM_admin_01

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

  batch:
    jdbc:
      initialize-schema: never